#!/usr/bin/env php
<?php

error_reporting(0);
require_once __DIR__ . '/lib/AmazonECS.class.php';

function term_echo($whatever, $error = false) {
  if ($error) {
    fprintf(STDERR, $whatever . "\n\n");
  } else {
    fprintf(STDOUT, $whatever . "\n\n");
  }
}

function show_help($extra = '') {
  $help = <<<HELP
    Usage: 
      {$argv[0]} "trackname"
    Example: 
      {$argv[0]} "Nirvana - Nevermind"
    Requirements:
      environment access AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY and AMAZON_AFFILIATE_ID
HELP;
  term_echo($help);

  if ($extra) {
    term_echo($extra, 1);
  }
}

try {
  if (! isset($argv[1]))
    throw new Exception("Script Requires First Argument Trackname");

  $ENV = $_ENV;

  if (! $ENV) {
    $ENV = $_SERVER;
  }

  if (
    ! isset($ENV['AMAZON_ACCESS_KEY_ID']) 
    || ! isset($ENV['AMAZON_SECRET_ACCESS_KEY'])
    || ! isset($ENV['AMAZON_AFFILIATE_ID'])
    )
    throw new Exception("Must export AMAZON_ACCESS_KEY_ID, AMAZON_SECRET_ACCESS_KEY and AMAZON_AFFILIATE_ID");
} catch (Exception $e) {
  show_help($e->getMessage());
}

$client = new AmazonECS(
  $ENV['AMAZON_ACCESS_KEY_ID'],
  $ENV['AMAZON_SECRET_ACCESS_KEY'],
  'com',
  $ENV['AMAZON_AFFILIATE_ID']
);

$response = $client->category('DigitalMusic')->responseGroup('Images')->search($argv[1]);

if (getType($response->Items->Item) == 'object') {
    term_echo($response->Items->Item->LargeImage->URL);
} elseif (getType($response->Items->Item) == 'array') {
    term_echo($response->Items->Item[0]->LargeImage->URL);
} else {
  term_echo('Not Found!');
}